services:
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - /home/cloud/.cache/huggingface:/root/.cache/huggingface
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - CUDA_LAUNCH_BLOCKING=1
      - MAX_JOBS=1
    command: ["--model", "facebook/opt-125m"]